# -*- coding: utf-8 -*-
"""pages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stfdrz0Msc4DVNoEyNhLGsrjQooRF4CR
"""

#pages/1_EDA.py
!pip install streamlit
import pandas as pd
import streamlit as st

import streamlit as st
import pandas as pd

st.title("📊 Exploratory Data Analysis")

st.write("Dataset Overview")

salary_df = pd.read_csv("/content/ds_salaries.csv")

st.dataframe(salary_df.head())

st.write("Rows:", salary_df.shape[0])
st.write("Columns:", salary_df.shape[1])

#pages/2_ATS_Score.py
import streamlit as st

st.title("📄 ATS Resume Score")

st.metric(
    label="ATS Score",
    value="40%"
)

#pages/3_Skill_Gap.py
import streamlit as st

st.title("🧠 Skill Gap Analysis")

st.write("This page will compare candidate skills with required skills.")

#pages/4_Job_Recommendation.py
import streamlit as st

st.title("💼 AI Job Recommendation")

st.write("Top recommended jobs will appear here.")

#pages/5_Salary_Analytics.py
import streamlit as st

st.title("📈 Salary Analytics")

st.write("Salary charts will be displayed here.")

#pages/6_Salary_Prediction.py
import streamlit as st

st.title("💰 Salary Prediction")

st.write("Predict salary using Machine Learning.")

#pages/7_Resume_Ranking.py
import streamlit as st

st.title("🏆 Resume Ranking")

st.write("Rank candidates based on ATS score.")

#pages/8_About.py
import streamlit as st

st.title("ℹ️ About")

st.write("""
AI Resume & Job Market Analytics

Built using:
- Python
- Streamlit
- Pandas
- Scikit-learn
- Machine Learning
""")

